@startuml X mappings
hide empty members
hide circle
abstract class  "X key name"
"X key name" <|-- "Alias X key name"
"X key name" <|-- "Canonical X key name"
"Alias X key name" "0..*" -- "1" "X keycode" : evdev 
"Canonical X key name" "1" -- "1" "X keycode" : evdev 

abstract class "Keysym entry"
"X key name" -- "0..*" "Keysym entry" : xkb_symbols

abstract class "Keysym mnemonic" {
  deprecated: bool
}
"Keysym entry" <|-- "Keysym mnemonic"
"Keysym entry" <|-- "Unicode code point"
"Keysym entry" <|-- "Keysym code"
"Keysym mnemonic" <|-- "Canonical Keysym mnemonic"
"Keysym mnemonic" <|-- "Alias Keysym mnemonic"
"Keysym mnemonic" "0..*" -- "0..1" "Unicode code point" : .h
"Canonical Keysym mnemonic" "0..1" -- "1" "Keysym code" : .h
"Alias Keysym mnemonic" "0..*" -- "1" "Keysym code" : .h
"Keysym code" "0..1" -- "0..1" "Unicode code point" : .h
@enduml